---
sidebar: sidebar
permalink: install-setup/cluster-setup.html
keywords: afx, afx system, cluster setup, setup
summary: ""
---
= Set up your AFX storage system ONTAP cluster
:icons: font
:imagesdir: ../media/

[.lead]
After your AFX hardware has been installed, you can complete the ONTAP cluster setup. This process involves related configuration phases that you should perform sequentially. As part of this, you can optionally add DX50 data compute nodes (DCNs) running the AI Data Engine (AIDE), enabling the AFX storage cluster and DCN cluster to operate as a single system that's managed through the same ONTAP control plane.

== Prepare to set up an AFX storage system

Before setting up your ONTAP cluster, you should review the core AFX requirements and additional AIDE considerations to ensure you have all the necessary information and resources to complete the setup process successfully.

=== Core AFX requirements

There are several core requirements to consider when setting up your AFX cluster.

.Hardware installation

Make sure you've completed the hardware installation of your AFX system. For more information, see link:../install-setup/install-setup-workflow.html[Install your AFX system].

.Basic IP addressing

You need the following IP addressing configuration:

* Cluster management IP address
+
The cluster management IP address is a unique IPv4 address for the cluster management interface used by the cluster administrator to access the admin SVM and manage the cluster. You can obtain this IP address from the administrator responsible for assigning IP addresses in your organization.

* Network subnet mask
+
During cluster setup, ONTAP requires a set of network interfaces appropriate for your configuration.  You can adjust the recommendation if necessary.

.Additional network configuration

You'll also need the following related networking information:

* Network gateway IP address
* DNS domain names
* DNS name server IP addresses
* NTP server IP addresses
* Subnet mask

=== Additional AIDE considerations

When installing and setting up AFX for the first time, you can optionally include NetApp AI Data Engine (AIDE). If you plan to set up AIDE, you'll need to first do the following:

* Make sure to https://docs.netapp.com/us-en/ai-data-engine/install-setup/aide-hardware-requirements.html[install AIDE^] and attach the compute nodes to the AFX storage network.

https://review.docs.netapp.com/us-en/ai-data-engine_aide-initial-release/install-setup/aide-hardware-requirements.html

* Obtain the addresses and any related network configuration for the DX50 data compute nodes.

== Perform initial cluster setup

You can connect your laptop device to the AFX cluster and set several global configuration values.

.About this task

There are four areas of the AFX cluster that must be initially configured. The first three are required while the last one is optional.

.Before you begin

.Steps

. Discover your cluster network.
.. Connect your laptop to the management switch and access the network computers and devices.
.. Open File Explorer.
.. Select *Network*; then right-click and select *Refresh*.
.. Select either ONTAP icon; then accept any certificates displayed on your screen.
+
The System Manager user interface is displayed.

. Set the administrator password.
+
Provide and verify the password for the `admin` account. Select *Continue*.

. Configure the IP addresses for the AFX cluster and controller nodes.
+
Provide IP addresses and the subnet masks.

. If you’re installing AI Data Engine with your AFX storage system, provide the IP addresses for the three AIDE DCN nodes.

. Configure the network services including DNS and NIS. Select *Continue*.
+
Define the details for your DNS and NTP servers.

. Optionally set up encryption.
+
You can define the details for cluster encryption. Select *Continue*.
+ 
NOTE: For information on how to create a cluster for a non-Windows environment, see link:https://docs.netapp.com/us-en/ontap/software_setup/setup-cluster.html[Create an ONTAP cluster and join nodes^].

.What's next

You'll be redirected to the System Manager sign-in page. Perform the steps described in <<Complete cluster setup>>.

== Complete cluster setup

After the initial configuration has been performed you can complete the ONTAP cluster setup using System Manager.

.About this task

There are three areas of the AFX system ONTAP cluster configured during setup. Complete all three if possible but only the first is required.

.Before you begin

You need to have the following information:

* VLAN configuration details.
* NAS and/or S3 configuration details.

.Steps

. Sign in to System Manager using the administrator account you provided during initial cluster setup. Notice the popup window at the top right with three configuration options.

. Select *VLAN and tagging* and select the network options appropriate for your environment.

. Select *Network Services* and configure the client access protocols for the default data SVM.

. Select *Data container* and create a volume or S3 bucket.

.What's next

* If you have included AIDE as part of the AFX cluster setup, you'll need to perform additional configuration steps including licensing and authentication. See https://docs.netapp.com/us-en/ai-data-engine/install-setup/cluster-setup-afx.html[Set up AI Data Engine^] for more information.

* You should link:../get-started/prepare-cluster-admin.html[Prepare to administer AFX] before using your AFX cluster in a production environment.

== Related information

* link:../get-started/learn-about-aide.html[Learn about the NetApp AI Data Engine]
* link:../administer/configure-svm.html[Configure an AFX SVM]
* link:../get-started/prepare-cluster-admin.html[Prepare to administer AFX]
