---
sidebar: sidebar
permalink: faq/faq-interoperate-ontap-afx.html
keywords: 
summary: 
---

= Interoperability FAQ for ONTAP AFX
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This FAQ list provides answers to questions that customers typically have about their ONTAP AFX storage systems. It focuses in interoperability and any current gaps.

.Can I use disaggregated ONTAP in the same cluster as Unified ONTAP? 

No. Disaggregated ONTAP and Unified ONTAP cannon co-exist within the same cluster. 

.If I want to use Unified ONTAP with disaggregated ONTAP for SnapMirror or FlexCache, what ONTAP version will I need?

SnapMirror version rules for Unified ONTAP are identical for disaggregated ONTAP. This means that to replicate from Unified ONTAP, the source system must be within the supported version range. To replicate from disaggregated ONTAP, the Unified ONTAP system must be at ONTAP 9.16.1 or later (that is, the earliest release Advanced Capacity Balancing is supported). For FlexCache, the same rules apply for source and destination systems as provided in https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf[TR-4743].
