---
sidebar: sidebar
permalink: secure-data/prepare-secure-data.html
keywords: 
summary: 
---

= Prepare to secure your ONTAP AFX data
:icons: font
:imagesdir: ../media/

[.lead]
Before managing your ONTAP AFX data, you should be familiar with the major concepts and capabilities.

[TIP]
Most of the concepts and procedures used for ONTAP AFX data security are the same as Unified ONTAP. Review the resources available in <<Related information>> for more information including the applicable Unified ONTAP documentation.

== Terminology and options

There are several terms related to ONTAP AFX data security you should be familiar with.

Ransomware::
Ransomware is malicious software that encrypts files, making them inaccessible to the user, and which typically demands some type of payment for decryption of the data. NetApp ONTAP provides solutions to protect against ransomware through features like Autonomous Ransomware Protection (ARP) and FPolicy.

Encryption::
Encryption is process of converting data into a secure format that cannot be easily read without proper authorization. ONTAP offers both software-based and hardware-based encryption technologies to protect data at rest. This ensures it cannot be read if the storage medium is repurposed, returned, misplaced, or stolen. These encryption solutions can be managed using either an external key management server or the Onboard Key Manager provided by ONTAP.

== Related information

* https://docs.netapp.com/us-en/ontap/authentication-access-control/index.html[Unified ONTAP Authentication and access control^]
* https://docs.netapp.com/us-en/ontap/security-encryption/index.html[Unified ONTAP Security and data encryption]
* link:../administer/additional-ontap-svm.html[Additional ONTAP AFX SVM administration]
