---
sidebar: sidebar
permalink: secure-data/ransomware-protection.html
keywords: 
summary: 
---
= Protect against ransomware attacks on ONTAP AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
For enhanced protection against ransomware attacks, you can replicate snapshots to a remote cluster and then lock the destination snapshots to make them tamper-proof. You can use locked snapshots to recover data if your system is ever compromised by a ransomware attack.

>> It uses workload analysis of the NAS environments to detect abnormal activity that might indicate an attack.

[TIP]
Locked snapshots cannot be deleted including accidentally or maliciously.

Add any restrictions with ONTAP AFX, such as ARP/AI not supported. Model after ASA r2: https://docs.netapp.com/us-en/asa-r2/secure-data/ransomware-protection.html[Protect against ransomware attacks on ASA r2 storage systems^]

.Related information

* https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html[Learn about ONTAP Autonomous Ransomware Protection^]

* https://docs.netapp.com/us-en/ontap-technical-reports/ransomware-solutions/ransomware-overview.html#data-is-the-primary-target[Ransomware and NetApp's protection portfolio^]
