---
sidebar: sidebar
permalink: faq.html
keywords: 
summary: 
---

= Frequently asked questions about ONTAP AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
This FAQ list provides answers to questions that customers have about ONTAP AFX storage systems. It contains concepts and terminology that can be valuable when exploring AFX in more detail and performing advanced cluster or SVM administration.

// --- Additional topics (see terminology section in advanced admin)
// What is an ONTAP personality?
// What are the available personalities?
// automated topology management (ATM)
// volume placement and the API
// zero copy volume move
// ---

.What does "disaggregated" mean with the ONTAP AFX storage systems?

The term "disaggregated" can have two different though related meanings with ONTAP AFX. The first concept is based on decoupling the compute capability in the controller nodes from the storage shelves. With ONTAP AFX, the cluster compute and storage components are no longer tightly coupled as they are with unified ONTAP. Rather, they are connected through one or more cluster switches. Each controller has a complete view of the storage pool. The second concept, which is largely a result of the decoupling, is that the aggregates and RAID management are removed as administrable entites. The AFX storage abstraction layer automatically configures and manages the aggregates and physical disks and RAID groups. The AFX administrator can focus on the higher level storage configuration based on volumes and buckets.
