---
settings:
  name: ndac
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true

sidebar:
  entries:
  - title: ONTAP AFX docs
    url: /index.html
  - section: release-notes
  - section: get-started
  - section: administer
  - section: svm-admin
  - section: rest
  - section: learn-more
  - title: FAQ
    url: /faq.html
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: ONTAP  
  repo: ontap-family