---
settings:
  name: AFX
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true

sidebar:
  entries:
  - title: AFX docs
    url: /index.html
  - section: release-notes
  - section: get-started
  - section: administer
  - section: svm-admin
  - title: Maintain hardware
    url: /maintain-hardware.html
  - section: rest
  - section: learn-more
  - title: FAQ
    url: /faq-ontap-afx.html
  - title: Legal notices
    url: /legal-notices.html

product-family:
  name: ONTAP  
  repo: ontap-family