---
sidebar: sidebar
permalink: protect-data/create-peer-relationship.html
keywords: afx, afx system, peering, peer relationship
summary: "A peer relationship defines network connections that enable clusters and storage virtual machine (VM) to exchange data securely. You can create a peer relationship between storage VMs on different clusters to enable data protection and disaster recovery using SnapMirror."
---
= Create an intercluster SVM peer relationship on AFX
:icons: font
:imagesdir: ../media/

[.lead]
A peer relationship defines network connections that enable clusters and storage virtual machine (VM) to exchange data securely. You can create a peer relationship between storage VMs on different clusters to enable data protection and disaster recovery using SnapMirror.

.Before you begin

You must have established a cluster peer relationship between the local and remote clusters before you can create a storage VM peer relationship.  link:snapshot-replication.html#step-1-create-a-cluster-peer-relationship[Create a cluster peer relationship] if you have not already done so.

.Steps

. In System Manager, select *Protection > Overview*.
. Under *Storage VM peers* select *Add a storage VM peer*.
. Select the storage VM on the local cluster; then select the storage VM on the remote cluster.
. Select *Add a storage VM peer*.

.Related information

* https://docs.netapp.com/us-en/ontap/peering/peering-basics-concept.html[Learn more about peer relationships^].
