---
sidebar: sidebar
permalink: protect-data/prepare-protect-data.html
keywords: afx, afx system, prepare, prepare protect, prepare protect data
summary: "Before protecting your AFX data, you should be familiar with some of the key concepts and current status of your storage."
---

= Prepare to protect your AFX storage system data
:icons: font
:imagesdir: ../media/

[.lead]
Before protecting your AFX data, you should be familiar with some of the key concepts and capabilities.

[TIP]
Because many of the concepts and administration procedures available on AFF and FAS systems are the same with AFX storage systems, reviewing the Unified ONTAP documentation can be helpful.

== Terminology and options

There are several terms related to AFX data protection you should be familiar with.

Snapshot::
A snapshot is a read-only, point-in-time image of a volume. It is a foundational technology for ONTAP's replication and data protection services.

Consistency group::
A consistency group is a collection of volumes that are managed as a single unit. You can create consistency groups to simplify storage management and data protection for application workloads. For example, you can snapshot several volumes in one operation by using the consistency group instead of the individual volumes.

Hierarchical consistency group::
Hierarchical consistency groups were introduced with ONTAP 9.16.1 and are available with AFX. With a hierarchical structure, one or more consistency groups can be configured as children under a parent. These hierarchical groups allow you to apply individual snapshot policies to child consistency groups and replicate the snapshots of all the children to a remote cluster as a single unit by replicating the parent.

SnapLock::
SnapLock is an ONTAP feature that allows you to protect your files by moving them to a write once read many (WORM) state. This prevents modification or deletion for a specified retention period. SnapLock volumes are created cannot be converted from non-SnapLock volumes after creation based on the retention.

== AFX data protection limitations

There are several limitations related to the ONTAP data protection features enforced by the AFX storage system.

.SnapMirror Synchronous (SM-S)
There is a scale limitation for SMS-S. You can have a maximum of 400 relationships across a single AFX system cluster.

== Related information

* link:../administer/additional-ontap-svm.html[Additional AFX SVM administration]
* link:../get-started/prepare-cluster-admin.html[Prepare to your administer AFX system]

// ONTAPDOC-3409 - DMP - Oct 14 2025
