---
sidebar: sidebar
permalink: protect-data/prepare-protect-data.html
keywords: 
summary: 
---

= Prepare to protect your ONTAP AFX data
:icons: font
:imagesdir: ../media/

[.lead]
Before protecting your ONTAP AFX data, you should be familiar with some of the key concepts and current status of your storage.

[TIP]
Most of the concepts and procedures used for data protection with ONTAP AFX are the same as Unified ONTAP. Refer to <<Related information>> for more information including links to the applicable Unified ONTAP documentation.

== Data protection terminology and options

There are several terms related to ONTAP AFX storage protection you should be familiar with.

Snapshot::
A snapshot is a read-only, point-in-time image of a volume. It is a foundational technology for ONTAP's replication and data protection services.

Consistency group::
A consistency group is a collection of volumes that can be managed as a single unit. You can create consistency groups to simplify storage management and data protection for application workloads. For example, you can snapshot several volumes in one operation by using the consistency group instead of the individual volumes.

== Related information

* link:../administer/additional-ontap-svm.html[Additional ONTAP AFX SVM administration]
