---
sidebar: sidebar
permalink: manage-data/prepare-provision-storage.html
keywords: 
summary: 
---
= Prepare to provision ONTAP AFX storage
:icons: font
:imagesdir: ../media/

[.lead]
xxx

*Add section with overview on quotas and qtrees*

>> Exporting data and client access MOVES TO THE TWO CREATE/ACCESS TOPICS

>> Review volume create (more options) and edit to get a list of the configuration options to describe

>> For example, have two options (data protection and high throughput), describe what these mean

== Storage terminology and options

xxx

Data container::
xxx volume or bucket

FlexVolume::
xxx

FlexGroup::
xxx

S3 bucket::
xxx

NFS trunking::
NFS trunking is a technology that enables NFS v4.1 clients to open multiple connections to different LIFs on the NFS server. This increases the data transfer speed and provide resilience through multi-pathing. Trunking is beneficial for exporting FlexVol volumes to trunking-capable clients.

== Storage limits

There are several storage limits, both minimums and maximums, enforced by ONTAP AFX. These are displayed by release.

=== ONTAP 9.17.1

.Node controllers per cluster

There is a minimum of four nodes and a maximum of eight.

== Client authentication and authorization options

>> Move to secure data section in SB? Separate topic?

>> intro, overview

>> link to UOD if needed

>> Create users?

== ONTAP AFX support for NFS trunking

xxx

>> To enable trunking, you need to have an SVM configured for NFS, and NFSv4.1 should be enabled. It requires remounting all NFSv4.x clients, which can be disruptive.

.Related information

* link:../administer/additional-ontap-svm.html[More details on NFS trunking]

== File system analytics

xxx
