---
sidebar: sidebar
permalink: administer/additional-ontap-svm.html
keywords: 
summary: 
---
= Additional ONTAP AFX SVM administration and features
:icons: font
:imagesdir: ../media/

[.lead]
In addition to the common ONTAP AFX SVM administration tasks, there are other tasks you may need to perform based on your environment. Most of these additional tasks can be performed using System Manager, although in some cases one of the other administrative interfaces may be needed.

*=> DP: See EAP for ideas*

.Related information

* link:../faq.html[Frequently asked questions about ONTAP AFX storage systems]

== Security

xxx

=== Manage SVM user accounts and roles

xxx

>> Provide an introduction and then a brief example; possibly link to the unified ONTAP doc; note that when creating an SVM there is an option to add an SVM level account.

== Exporting data and client access

xxx

=== NFS trunking

xxx

*Already have this content here:*

link:../manage-data/prepare-manage-data.html[Prepare to manage your ONTAP AFX data]

== Data protection

xxx

*Provide a brief summary, don't repeat the prepare topic under GS.*

=== Cloud backup

xxx
