---
sidebar: sidebar
permalink: administer/additional-ontap-svm.html
keywords: afx, afx system, additional administration, advanced administration
summary: "In addition to the typical AFX SVM administration, there may be other tasks you need to perform based on your environment. Most of the additional tasks can be performed using System Manager, although in some cases you may need to use the CLI."
---
= Additional administration for an AFX storage system SVM
:icons: font
:imagesdir: ../media/

[.lead]
In addition to the typical AFX SVM administration, there may be other tasks you need to perform based on your environment. Most of the additional tasks can be performed using System Manager, although in some cases you may need to use the CLI.

[NOTE]
The features and AFX administration described are common to AFX storage systems and AFF or FAS systems running Unified ONTAP. Links to the relevant Unified ONTAP documentation are included as appropriate.

== Storage management and performance

There are several optional storage management and performance features you can configure and use with your AFX deployment.

=== NAS storage management

Network Attached Storage (NAS) provides dedicated file storage which can be accessed by multiple clients in the network. ONTAP supports several NAS protocols. See https://docs.netapp.com/us-en/ontap/nas-management/index.html[NAS storage management^] for more information.

=== FlexCache

FlexCache is an ONTAP remote caching feature. It brings data closer to clients which improves access performance and reduces costs. It simplifies file distribution and reduces WAN traffic by creating a FlexCache volume, which initially copies only the metadata from the origin file system. See https://docs.netapp.com/us-en/ontap/flexcache/index.html[Learn about ONTAP FlexCache volumes^] for more information.

== ONTAP event and performance monitoring

You can monitor the health and performance of a cluster. This includes setting up alerts for events and managing notifications for system health alerts. See https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html[Event, performance, and health monitoring^] for more information

.Related information

* link:../faq-ontap-afx.html[FAQ for AFX storage systems]
* https://docs.netapp.com/us-en/ontap/nas-management/index.html[NAS storage management^]
* https://docs.netapp.com/us-en/ontap/flexcache/index.html[Learn about ONTAP FlexCache volumes^]
* https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html[Event, performance, and health monitoring^]
