---
sidebar: sidebar
permalink: administer/advanced-svm.html
keywords: 
summary: 
---
= ONTAP AFX advanced SVM administration
:icons: font
:imagesdir: ../media/

[.lead]
You can use System Manager to perform most of the administrative tasks needed to support an ONTAP AFX SVM. However, depending on your deployment environment and goals, you may need to use one of the other administrative interfaces as well. You should be familiar with these advanced administration tasks using the ONTAP AFX command line interface.

*=> DP: This page is included to align with the cluster admin page. However if there is no applicable content it will be removed.*

.Related information

* link:../faq.html[Frequently asked questions about ONTAP AFX storage systems]
* link:../administer/additional-ontap-svm.html[Additional ONTAP AFX SVM configuration]

== Concepts and terminology

There are several concepts that can apply when you are performing advanced administration tasks with the ONTAP AFX storage system.

*=> DP: Is there any SVM-specific terminology?*

== Advanced configuration procedures

There are situations where you may need to use the ONTAP AFX to perform SVM administration tasks.

=== Manage SVM user accounts and roles

xxx

>> Provide an introduction and then a brief example; possibly link to the unified ONTAP doc
