---
sidebar: sidebar
permalink: administer/expand-cluster.html
keywords: 
summary: 
---
= Expand the ONTAP AFX cluster node controllers
:icons: font
:imagesdir: ../media/

[.lead]
You can expand the compute capability of an ONTAP AFX independent of the storage capacity. This can be a significant benefit as you adjust to the ongoing needs of your storage users.

.About this task

This procedure describes how to add two compute nodes to an existing cluster. You'll need to use both the ONTAP CLI and System Manager administrative interfaces.

.Before you begin

You need to have the credentials for a cluster administrator account and connect to the ONTAP CLI using SSH.

.Steps

. After connecting to the ONTAP CLI, set advanced privilege mode:
+
`afx> set advanced`

. Check the volume location of the current nodes; note the number of volumes per node:
+
`afx> vol show -fields node,size,constituent-count -is-constituent true -node *`

. Collect the cluster interconnect IP addresses and save them for use in later steps:
+
`afx> net int show -role Cluster`

.What's next?

You should monitor the updated cluster and continue to adjust the configuration as needed.
