---
sidebar: sidebar
permalink: administer/monitor-cluster-performance.html
keywords: 
summary: 
---
= Monitor ONTAP AFX cluster performance
:icons: font
:imagesdir: ../media/

[.lead]
You display a high-level view of your ONTAP AFX cluster, including storage usage and general performance.

.Related information

* link:../administer/advanced-cluster.html[ONTAP AFX advanced cluster administration]

== Storage capacity

The System Manager dashboard includes a high-level display of the storage utilization for the cluster.

.Steps

. In System Manager, select *Dashboard* in the navigation pane.

. Locate the *Capacity* tile and note the physical storage available and used.

. Select *History* to access Active IQ and view the historical data.

== Cluster performance

System Manager provides a detailed overview of the overall ONTAP AFX cluster performance.

.Steps

. In System Manager, select *Analysis* and then *Performance*.

. Review the cluster performance summary at top including latency and throughput.

. Under the *Top actors* tab, select the desired SVM and then *Enable activity tracking*.

. Under the *Volume performance* tab, view the performance details and a specific volume if needed.
