---
sidebar: sidebar
permalink: administer/upgrade-ontap.html
keywords: afx, afx system, upgrade, upgrade ontap
summary: "When you upgrade your ONTAP software on your AFX system, you can take advantage of new and enhanced ONTAP features that can help you reduce costs, accelerate critical workloads, improve security, and expand the scope of data protection available to your organization."
---

= Upgrade ONTAP on an AFX storage system
:icons: font
:imagesdir: ../media/

[.lead]
When you upgrade your ONTAP software on your AFX system, you can take advantage of new and enhanced ONTAP features that can help you reduce costs, accelerate critical workloads, improve security, and expand the scope of data protection available to your organization.

[CAUTION]
AFX storage systems do not support link:../administer/revert-ontap.html[ONTAP revert] operations. 

ONTAP software upgrades for AFX storage systems follow the same process as upgrades for other ONTAP systems.  If you have an active SupportEdge contract for Active IQ Digital Advisor (also known as Digital Advisor), you should link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html[prepare to upgrade with Upgrade Advisor^]. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your cluster and creating an upgrade plan specific to your configuration. If you don't have an active SupportEdge contract for Active IQ Digital Advisor, you should link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html[prepare to upgrade without Upgrade Advisor^].

After you prepare for your upgrade, it is recommended that you perform upgrades using link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html[automated non-disruptive upgrade (ANDU) from System Manager]. ANDU takes advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade.

.Related information

* https://docs.netapp.com/us-en/ontap/upgrade/index.html[Learn about ONTAP upgrade^].

== Execute automated pre-upgrade checks before a planned upgrade

You don't have to be in the process of upgrading your ONTAP software to execute the ONTAP automated upgrade pre-checks. Executing the pre-upgrade checks independently of the ONTAP automated upgrade process allows you to see which checks are performed against your cluster and gives you a list of any errors or warnings that should be corrected before you begin the actual upgrade. 

Beginning with ONTAP 9.19.1, errors and warning are displayed separately to help you easily identify issues that must be resolved before you upgrade.  

link:https://docs.netapp.com/us-en/ontap/upgrade/automated-pre-checks.html[Learn to execute ONTAP automated pre-upgrade checks^].

// 2026 May 07, ONTAPDOC-3602

