---
sidebar: sidebar
permalink: administer/upgrade-ontap.html
keywords: 
summary: 
---

= Upgrade ONTAP on an AFX storage system
:icons: font
:imagesdir: ../media/

[.lead]
When you upgrade your ONTAP software on your ONTAP AFX system, you can take advantage of new and enhanced ONTAP features that can help you reduce costs, accelerate critical workloads, improve security, and expand the scope of data protection available to your organization.

//https://confluence.ngage.netapp.com/display/TOI/ANDU+and+OAM[ANDU and OAM^]

ONTAP software upgrades for ONTAP AFX storage systems follow the same process as upgrades for other ONTAP systems.  If you have an active SupportEdge contract for Active IQ Digital Advisor (also known as Digital Advisor), you should link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html[prepare to upgrade with Upgrade Advisor^]. Upgrade Advisor provides intelligence that helps you minimize uncertainty and risk by assessing your cluster and creating an upgrade plan specific to your configuration. If you don't have an active SupportEdge contract for Active IQ Digital Advisor, you should link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html[prepare to upgrade without Upgrade Advisor^].

After you prepare for your upgrade, it is recommended that you perform upgrades using link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html[automated non-disruptive upgrade (ANDU) from System Manager]. ANDU takes advantage of ONTAP’s high-availability (HA) failover technology to ensure that clusters continue to serve data without interruption during the upgrade.

.Related information

* https://docs.netapp.com/us-en/ontap/upgrade/index.html[Learn about ONTAP upgrade^].
