---
sidebar: sidebar
permalink: get-started/compare-unified-ontap.html
keywords: 
summary: 
---
= Compare AFX to Unified ONTAP
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of how AFX is similar to and different from Unified ONTAP. This provides a valuable perspective and can be helpful when deploying AFX in your environment.

== New platform built on Unified ONTAP

AFX is initially based on the Unified ONTAP personality. Because of this, it includes a robust set of features and administrative options. If you're an experienced ONTAP user, you'll find it very easy to work with AFX. If you're new to ONTAP, the simplified System Manager user interface and streamlined administration will help you get started quickly.

== Configuration differences with Unified ONTAP

There are a few areas where the default AFX configuration differs from Unified ONTAP.

Advanced Capacity Balancing::
The advanced capacity balancing feature, as controlled using the `-gdd` CLI parameter, is enabled by default for all FlexGroup volumes.

== Unsupported or restricted Unified ONTAP capabilities

While the AFX and Unified ONTAP personalities are very similar, there are several features that are not supported with AFX.

[TIP]
You should review the updates and changes for AFX in the appropriate link:../release-notes/whats-new-9171.html[What's new] section based on your release.

The following features, organized in several categories, are not available or have changed with AFX.

=== General features

[big red]*DP: Chris will confirm whether to remove SnapLock from the list.*

* FabricPool
* SnapLock
* MetroCluster
* AI based anti-ransomware protection
* ONTAPI API (ZAPI)
//* Active IQ Unified Manager

=== SAN-related features

* SAN administration and client access
* Thick provisioned volumes

=== Aggregate-related features

The following aggregate-related features are not available with AFX:

* Direct access to disk aggregates
* NetApp Aggregate Encryption (NAE)
* Aggregate-level deduplication
* SyncMirror (aggregate mirroring)
* RAID management
// NetApp Volume Encryption (NVE) and self-encrypting volumes ARE supported

=== Data replication

* No replication of a volume from Unified ONTAP that contains a LUN
* FlexGroup volumes can only be replicated to ONTAP 9.16.1 or later

== Changes to the command line interface

The CLI available with AFX generally mirrors Unified ONTAP. But there are several differences, including:

* New AFX commands related to:
** Displaying the capacity of the storage availability zone
** Boot media

* No SAN-related commands 

* Aggregate management commands are no longer required

* FlexAggr commands can only display or show the FlexAggrs

== Related information

* link:../get-started/system-design.html[AFX system characteristics]
* link:../get-started/software-architecture.html[Details of the AFX architecture]
* link:../faq-ontap-afx.html[FAQ for AFX storage systems]
