---
sidebar: sidebar
permalink: get-started/compare-unified-ontap.html
keywords: afx, afx system, compare afx, compare unified ontap
summary: "NetApp AFX systems run a customized personality of ONTAP that differs from the ONTAP personality (referred to as Unified ONTAP) that runs on AFF and FAS storage. You should be aware of how AFX systems are similar to and different than FAS and AFF systems. This provides a valuable perspective and can be helpful when deploying AFX in your environment."
---
= Compare AFX storage system to AFF and FAS systems
:icons: font
:imagesdir: ../media/

[.lead]
NetApp AFX systems run a customized personality of ONTAP that differs from the ONTAP personality (referred to as Unified ONTAP) that runs on AFF and FAS storage. You should be aware of how AFX systems are similar to and different than FAS and AFF systems. This provides a valuable perspective and can be helpful when deploying AFX in your environment.

[TIP]
The AFX documentation includes links to various topics at the Unified ONTAP doc site for details about features that behave in the same way regardless of the ONTAP personality. The additional content provides more depth that can be helpful as you administer your AFX storage system.

== Configuration differences

There are a few areas where the AFX configuration differs from AFF and FAS systems.

Advanced Capacity Balancing::
The advanced capacity balancing feature, controlled using the `-gdd` CLI parameter, is enabled by default for all FlexGroup volumes.

== Unsupported or restricted Unified ONTAP capabilities

NetApp AFX is optimized for high-performance NAS and object workloads. Because of this, there are differences with AFF and FAS as well as the other Unified ONTAP storage systems. The following features are not available with the NetApp AFX; the list is organized by major feature or functional area. You should also review the updates and changes for AFX in link:../release-notes/whats-new-9171.html[What's new] based on your release.

=== Block and SAN

* SAN administration and client access
* LUNs and NVMe namespaces
* Thick provisioning of volumes

=== Aggregates and physical storage

* MetroCluster
* Physical node-owned aggregates
* RAID management
* NetApp Aggregate Encryption (NAE)
* Aggregate-level deduplication
* SyncMirror (aggregate mirroring)
* FabricPool tiering

=== Data replication (SnapMirror)

[NOTE]
All data replication is supported in both directions between Unified ONTAP and AFX with the same versioning restrictions described in https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html[Compatible ONTAP versions for SnapMirror relationships^] (with a few minor exceptions).

* No replication of a volume from an AFF or FAS system that contains a LUN or NVMe namespace
* FlexGroup volumes can only be replicated from AFX to Unified ONTAP version 9.16.1 or later (because of the need for Advanced Capacity Balancing)

=== Manageability

* ONTAPI API (ZAPI)
* REST APIs for unsupported features (such as MetroCluster)
* Some initial limitations on REST APIs for performance statistics
* AIQ Unified Manager support
* Grafana Harvest version 25.08.1 and later
* NetApp Trident version 25.10 and later

== Changes to the command line interface

The ONTAP CLI available with AFX generally mirrors the CLI available with AFF and FAS systems. But there are several differences, including:

* New AFX commands related to:
** Displaying the capacity of the storage availability zone
** Boot media

* No SAN-related commands 

* Aggregate management commands are no longer required

* Aggregate show now displays the entire Storage Availability Zone (SAZ)

== Related information

* link:../get-started/system-design.html[AFX system characteristics]
* link:../get-started/software-architecture.html[Details of the AFX architecture]
* link:../faq-ontap-afx.html[FAQ for AFX storage systems]
* link:../administer/additional-ontap-cluster.html[Additional AFX cluster administration]
* link:../administer/additional-ontap-svm.html[Additional AFX SVM administration]
