---
sidebar: sidebar
permalink: get-started/ontap-afx-storage.html
keywords: 
summary: 
---
= Learn about ONTAP AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP AFX is a storage product that complements the existing NetApp offerings including Unified ONTAP available with FAS and AFF as well as ASA r2, E-Series, and StorageGRID. It's based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. ONTAP AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance.

// Comment to reviewers:
[big red]*DP: Please confirm the hardware infrastructure list at bottom. Are we missing anything in the list below?*

== Typical application workloads

ONTAP AFX is designed as a next generation data platform and is specifically targeted at the unique demands typical of AI/ML environments and other related data-centric applications. The AFX storage system is ideal for organizations managing several differnet workloads including:

* Training and iterative model refinement associated with deep learning where continuous high bandwidth and access to massive datasets is required.
* Processing diverse data types including text, images, and video.
* Real‑time inference applications with low latency where strict response time windows are needed.
* Data science and machine learning pipelines that can benefit from self‑service data management by data engineers and data scientists.
* Workloads that require high concurrency and parallel I/O, such as multi‑GPU systems with RDMA transport.

== Hardware infrastructure

The NetApp ONTAP AFX storage system delivers a unified hardware and software solution that creates a simplified experience specific to the needs of high-performance NAS customers.

The following hardware platforms are used with and support ONTAP AFX:

* AFX 1K
* NX224
* Cisco Switches 9332D and 9364D for AFX
