---
sidebar: sidebar
permalink: get-started/ontap-afx-storage.html
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco
summary: "The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance."
---
= Learn about AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance.

== Typical application workloads

The NetApp AFX storage system meets the unique demands typical of AI/ML environments and other related data-centric applications. The AFX storage system is ideal for organizations managing several different workloads including:

* Training and iterative model refinement associated with deep learning where continuous high bandwidth and access to massive datasets is required.
* Processing diverse data types including text, images, and video.
* Real‑time inference applications with low latency where strict response time windows are needed.
* Data science and machine learning pipelines that can benefit from self‑service data management by data engineers and data scientists.
* Workloads that require high concurrency and parallel I/O, such as multi‑GPU systems with RDMA transport.

== System design characteristics

The AFX system has several design characteristics that enable it to operate as a high-performance NAS platform.

Decouple storage and compute capabilities::
Unlike AFF and FAS storage systems, the AFX storage and compute elements of the cluster are decoupled. AFX controllers are not restricted to accessing a limited set of local disks.

Removal of aggregate and RAID management::
The storage administrator no longer needs to manage the aggregates and RAID groups. AFX handles these tasks which simplifies administration and provides an opportunity for nonspecialists to manage their data.

Single storage pool for the cluster::
Decoupling the AFX compute and storage, along with simplified storage management, results in a single pool of storage. This Storage Availability Zone (SAZ) is available to all the controller nodes in an AFX cluster. See link:../faq-ontap-afx.html[FAQ for AFX storage systems] for more details.

High performance::
AFX is built for the high performance needed by specialized AI/ML applications. It can make more efficient use of modern hardware to provide high and sustained bandwidth with ultra‑low latency.

Operational simplicity::
The single storage pool, along with other features including automatic storage management, provides a much simpler administrative and operational model.

Scalability::
The set of controller nodes and storage shelves in a cluster can be independently expanded based on the application needs. There are limited administration requirements and disruptions when adding controllers or shelves.

Improved data mobility::
Volumes can be moved among the cluster controller nodes non-disruptively without actually copying data. Metadata directory and index pointers are updated instead. This dramatically improves performance during typical administrative procedures as well as recovery in failure scenarios.

== Hardware infrastructure

The NetApp AFX storage system delivers a unified hardware and software solution that creates a simplified experience specific to the needs of high-performance NAS customers.

The following hardware components are used with AFX clusters:

* AFX 1K controllers
* NX224 shelves
* Cisco Nexus 9332D-GX2B or Nexus 9364D-GX2A switches

== Related information

* https://www.netapp.com/afx/[NetApp AFX^]
