---
sidebar: sidebar
permalink: get-started/ontap-afx-storage.html
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco
summary: "The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance."
---
= Learn about AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance.

== Typical application workloads

The NetApp AFX storage system meets the unique demands of NAS and S3 object workloads that require high performance and independent scale. These applications benefit from an advanced design built on high concurrency and parallel I/O. AFX is ideal for organizations deploying and managing several different application workloads including:

* Training and iterative model refinement associated with deep learning where continuous high bandwidth and access to massive datasets is required.
* Processing diverse data types including text, images, and video.
* Real‑time inference applications with low latency where strict response time windows are needed.
* Data science and machine learning pipelines that can benefit from self‑service data management by data engineers and data scientists.

== System design characteristics

The AFX system has several design characteristics that enable it to operate as a high-performance NAS platform.

Decouple storage and compute capabilities::
Unlike other NetApp ONTAP storage systems, the compute and storage elements of an AFX cluster are decoupled and joined through a switched network. Disk ownership is no longer tied to specific nodes which provides several benefits. For example, the compute and storage components of a cluster can be increased independently.

Automated storage management::
The physical aggregates are no longer available to the AFX storage administrator. Instead, AFX automatically manages the virtual capacity allocations for nodes, as well as RAID group configuration, when new storage shelves are added to the cluster. This design simplifies administration and provides an opportunity for nonspecialists to manage their data.

Single storage pool for the cluster::
Because the storage nodes and shelves are decoupled with NetApp AFX, all storage capacity is collected in a single pool of storage known as a Storage Availability Zone (SAZ). The disks and shelves in a SAZ are available for read and write operations to all the storage nodes in an AFX cluster. In addition, all the cluster nodes can participate in disk rebuilds in the event of a failure. Refer to link:../faq-ontap-afx.html[FAQ for AFX storage systems] for more details.

High performance::
NetApp AFX is built for high performance NAS and object workloads, and provides high and sustained bandwidth with ultra-low latency. AFX uses the latest modern hardware as well as storage shelves capable of handling a high ratio of nodes to disks through the unique architecture. Scaling storage nodes beyond the typical 1:1 (node:shelf) ratio maximizes the possible performance profile of the disks to their edge limits. This design provides efficiency and storage density for your most critical applications.

Independent and massive scale::
Based on the decoupled storage nodes and shelves, an AFX cluster can be independently and nondisruptively expanded based on your application needs. You can add storage nodes to get more CPU and throughput or add shelves to get more storage capacity and disk performance. The NetApp AFX architecture brings new possibilities to the maximum scale of your cluster. For the latest limits for the AFX cluster, refer to the NetApp Hardware Universe.

Improved data mobility::
Volumes can be moved among the cluster controller nodes non-disruptively without actually copying data. Metadata directory and index pointers are updated instead. This dramatically improves performance during typical administrative procedures as well as recovery in failure scenarios.

== Hardware infrastructure

The NetApp AFX storage system delivers a unified hardware and software solution that creates a simplified experience specific to the needs of high-performance NAS customers.

The following hardware components are used with AFX clusters:

* AFX 1K controllers
* NX224 shelves
* Cisco Nexus 9332D-GX2B or Nexus 9364D-GX2A switches

== Related information

* https://hwu.netapp.com/[NetApp Hardware Universe^]
* https://www.netapp.com/afx/[NetApp AFX^]
