---
sidebar: sidebar
permalink: get-started/ontap-afx-storage.html
keywords: afx, afx system, learn, workloads, hardware, afx 1k, nx224, cisco
summary: "The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance."
---
= Learn about AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
The NetApp AFX storage system is based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. AFX supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance.

== Typical application workloads

The NetApp AFX storage system meets the unique demands of NAS and S3 object workloads that require high performance and independent scale. These applications benefit from an advanced design built on high concurrency and parallel I/O. AFX is ideal for organizations deploying and managing several different types of application workloads including:

* Training and iterative model refinement associated with deep learning where continuous high bandwidth and access to massive datasets is required.
* Processing diverse data types including text, images, and video.
* Real‑time inference applications with low latency where strict response time windows are needed.
* Data science and machine learning pipelines that can benefit from self‑service data management by data engineers and data scientists.

== System design characteristics

The AFX system has several design characteristics that enable it to operate as a high-performance NAS platform.

Decouple storage and compute capabilities::
Unlike other NetApp ONTAP storage systems, the compute and storage elements of an AFX cluster are decoupled and joined through a switched network. Disk ownership is no longer tied to specific nodes which provides several benefits. For example, the compute and storage components of an AFX cluster can be expanded independently.

Automated storage management::
The physical aggregates are no longer available to the AFX storage administrator. Instead, AFX automatically manages the virtual capacity allocations for the nodes, as well as RAID group configuration, when new storage shelves are added to the cluster. This design simplifies administration and provides an opportunity for nonspecialists to manage their data.

Single storage pool for the cluster::
Because the storage nodes and shelves are decoupled with NetApp AFX, all storage capacity for the cluster is collected in a single pool known as a Storage Availability Zone (SAZ). The disks and shelves in a SAZ are available for read and write operations to all the storage nodes in an AFX cluster. In addition, all the cluster nodes can participate in disk rebuilds in the event of a failure. Refer to link:../faq-ontap-afx.html[FAQ for AFX storage systems] for more details.

High performance::
NetApp AFX provides high and sustained bandwidth with ultra-low latency and so is designed for high performance NAS and object workloads. AFX uses the latest modern hardware as well as storage shelves capable of handling a high ratio of nodes to disks through its unique architecture. Scaling storage nodes beyond the typical 1:1 (node:shelf) ratio maximizes the possible performance profile of the disks to their edge limits. This design provides efficiency and storage density for your most critical applications.

Independent and massive scale::
Based on the decoupled storage nodes and shelves, an AFX cluster can be independently and nondisruptively expanded based on your application needs. You can add storage nodes to get more CPU and throughput or add shelves to get more storage capacity and disk performance. The NetApp AFX architecture brings new possibilities to the maximum size of your cluster. For the latest limits for the AFX cluster based on your ONTAP release, refer to the NetApp Hardware Universe.

Zero copy data mobility::
NAS and object clients access volumes at the ONTAP cluster. You can relocate volumes across the nodes nondisruptively to achieve your capacity and performance balancing goals. With Unified ONTAP, a volume move is performed using SnapMirror technology which can take time and additional temporary capacity. But with AFX, a data copy operation is no longer needed within the shared Storage Availability Zone (SAZ). Instead, only the volume metadata is moved which dramatically improves performance. Refer to link:../faq-ontap-afx.html[FAQ for AFX storage systems] for more details.

//Improved data mobility::
//during typical administrative procedures as well as recovery in failure scenarios.

Enhanced HA functionality::
NetApp AFX offers a number of high availability (HA) enhancements. AFX removes the need to directly connect HA partner nodes and instead allows HA pairs to communicate over the backend cluster network switch. This design gives administrators the option of deploying HA pairs in separate racks or rows in a datacenter for added fault tolerance. In addition, the zero-copy mobility available with AFX extends to failover scenarios. For example, when a node fails its volumes failover to the HA partner in order to commit any lingering writes to disk. Then ONTAP balances the volumes evenly across all surviving nodes in the cluster. This means you no longer have to consider storage failover performance in initial design of your data placement.

== Hardware infrastructure

The NetApp AFX storage system delivers a unified hardware and software solution that creates a simplified experience specific to the needs of high-performance NAS customers.

[TIP]
You should review the link:../faq-ontap-afx.html[FAQ for AFX storage systems] for more information about hardware interoperability and upgrade options.

The following hardware components are used with AFX clusters:

* AFX 1K controllers
* NX224 shelves
* Cisco Nexus 9332D-GX2B or Nexus 9364D-GX2A switches

== Related information

* https://hwu.netapp.com/[NetApp Hardware Universe^]
* https://www.netapp.com/afx/[NetApp AFX^]
