---
sidebar: sidebar
permalink: get-started/ontap-afx-storage.html
keywords: 
summary: 
---
= ONTAP AFX storage systems
:icons: font
:imagesdir: ../media/

[.lead]
ONTAP AFX is a series of storage products that complement the existing NetApp offerings including Unified ONTAP available with FAS and AFF as well as ASA r2, E-Series, and StorageGRID.

NetApp AFX systems are based on a next‑generation storage architecture that evolves the ONTAP storage model into a disaggregated high-performance NAS solution. It supports both file and object workloads with advanced technologies and processing techniques that provide extremely high performance.

== Typical application workloads

ONTAP AFX is designed as a next generation data platform and is specifically targeted at the unique demands typical of AI/ML environments and other related data-centric applications. The AFX storage system is ideal for organizations managing several environments, including workloads such as:

* Training and iterative model refinement associated with deep learning where continuous high bandwidth and access to massive datasets is required.
* Processing diverse data types including text, images, and video.
* Real‑time inference applications with low latency where strict response time windows are needed.
* Data science and machine learning pipelines that can benefit from self‑service data management by data engineers and data scientists.
* Workloads that require high concurrency and parallel I/O, such as multi‑GPU systems with RDMA transport.

== Hardware infrastructure

*Need to confirm with SMEs about what content to add here, including hardware models. Will align with similar content in the following ASA r2 topic:*

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html[Learn about ASA r2 storage systems^]

Some of the hardware topics might include the following:

* AFX 1K
* NX224
* Cisco Switches 9332D and 9364D for AFX
