---
sidebar: sidebar
permalink: get-started/system-design.html
keywords: 
summary: 
---
= ONTAP AFX system design goals
:icons: font
:imagesdir: ../media/

[.lead]
There are several principles and goals guiding the design and evolution of ONTAP AFX storage systems.

.Decouple storage and compute capabilities

Unlike Unified ONTAP, the AFX storage and compute elements of the cluster are decoupled. The controllers are not restricted to accessing a limited set of local disks.

.Removal of aggregate and RAID management

The storage administrator no longer needs to directly manage the aggregates and RAID groups. ONTAP AFX handles this which simplifies administration and provides an opportunity for nonspecialists to manage their data.

.Single storage pool for the cluster

Decoupling the AFX compute and storage, along with simplified storage management, results in a large single pool of storage. The entire storage pool is available to all controller nodes in an AFX cluster.

.High performance

ONTAP AFX is built for the high performance needed by specialized AI/ML applications. It can make more efficient use of modern hardware to provide high and sustained bandwidth with ultra‑low latency.

.Operational simplicity

The single storage pool, along with other features including automatic storage management, provide a much simpler administrative and operational model.

.Scalability

The set of controller nodes and storage shelves in a cluster can be independently expanded based on the application needs. There are limited administration requirements and disruptions when adding controllers or shelves.

.High availability

With the traditional HA-pair architecture available with Unified ONTAP, concurrent failure of two nodes can result in data loss. AFX provides a more robust and resilient architecture supporting flexible partner selection as well as full _N-way_ configuration. This design tolerates concurrent failures without disruption or data loss.

.Improved data mobility

Volumes can be moved among the cluster controller nodes non-disruptively without actually copying data. Directory and index pointers are updated instead. This dramatically improves performance during typical administrative procedures as well as recovery in failure scenarios.
