---
sidebar: sidebar
permalink: release-notes/whats-new-9191.html
keywords: afx, release notes, what's new, 9.19.1
summary: "Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system."
---
= What's new in ONTAP 9.19.1 for AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system.

* Learn about https://docs.netapp.com/us-en/ai-data-engine/release-notes/whats-new.html[new and enhanced support for AI Data Engine^].

== Security

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| link:../administer/additional-ontap-cluster.html[Support for TLS hardware offload]
a| You can offload Transport Layer Security (TLS) encryption and decryption for your entire cluster to supported Ethernet cards.  This reduces CPU overhead and improves performance for systems using TLS.

// table end
|===

== Storage management

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| link:../administer/additional-ontap-cluster.html[System Manager support for storage availability zone capacity details.]
a| You can view your storage availability zone capacity details including space thresholds, space consumed by snapshots, and data reduction in System Manager. You can also set space usage thresholds to the percentage at which you want ONTAP to generate warning and critical alerts.

// table end
|===


== Upgrade

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| link:../administer/upgrade-ontap.html[Enhanced reporting for automated pre-upgrade checks]
a| When executing automated pre-upgrade checks, errors and warning are displayed separately to help you easily identify issues that must be resolved before you upgrade.

// table end
|===

.Related information

* https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP 9 release highlights^]

// 2026 May 07, ONTAPDOC-3603, ONTAPDOC-3501, ONTAPDOC-3614