---
sidebar: sidebar
permalink: release-notes/whats-new-9171.html
keywords: afx, release notes, what's new, 9.17.1
summary: "Learn about the new capabilities included with ONTAP 9.17.1 that are available with your AFX storage system."
---
= What's new in ONTAP 9.17.1 for AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the new capabilities included with ONTAP 9.17.1 that are available with your AFX storage system.

[NOTE]
There are several new features available for AFX with ONTAP 9.17.1. Some of these are specific to AFX while many others are derived from a common shared product base. In addition to reviewing the AFX features described below, you should also refer to https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9171.html[What's new in ONTAP 9.17.1^].

== Platforms

[cols="2,4" options="header"]
|===
| Update
| Description

| Platforms
a| The following NetApp AFX storage system components are available along with the related supporting technology. Together this platform delivers a unified hardware and software solution that creates a simplified experience specific to the needs of high-performance NAS and S3 customers.

* AFX 1K controllers
* NX224 shelves
* Cisco Nexus 9332D-GX2B and Nexus 9364D-GX2A switches

|===

== Storage resource management enhancements  

[cols="30%,70%",options="header"]
|===
| Update | Description 
a|
xref:../manage-data/monitor-debug-storage.html[Monitor and troubleshoot an AFX storage system]
a|
Volumes created on newly created SVMs on ONTAP clusters allocated for NAS protocols have File System Analytics (FSA) enabled by default. FSA is automatically activated as soon as a volume is created, providing immediate analytics capabilities without additional configuration.

|===

== Related information

* https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP 9 release highlights^]
