---
sidebar: sidebar
permalink: release-notes/whats-new-9191.html
keywords: afx, release notes, what's new, 9.19.1
summary: "Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system."
---
= What's new in ONTAP 9.19.1 for AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system.

[TIP]
Learn about the new and enhanced support for https://docs.netapp.com/us-en/ai-data-engine/release-notes/whats-new.html[AI Data Engine^].

== Performance and scale

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| Expanded AFX cluster size
a| ONTAP 9.19.1 supports the expansion of an AFX cluster to a maximum of 32 nodes. This allows you to scale your AFX storage system to meet the growing demands of your workloads and applications.

| Increased FlexGroup size
a| You can now increase the maximum size of a FlexGroup volume, allowing you to store and manage larger datasets more efficiently.

| Cross File Sequential Read (CFSR)
a| Cross File Sequential Read can significantly improve read performance for certain media and entertainment workloads. The feature intelligently prefetches sequential video frames to dramatically improve throughput and reduce latency for video editing applications. Review link:../administer/additional-ontap-svm.html[Additional administration for an AFX storage system SVM] for more information.

| Global deduplication
a| Global deduplication extends the existing ONTAP deduplication space savings to the entire Storage Availability Zone (SAZ). By eliminating duplicate data blocks across all the volumes in the SAZ, it can significantly improve storage efficiency and reduce total cost of ownership. The feature is enabled by default on AFX systems and operates transparently without the need for administrative configuration. Refer to link:../administer/additional-ontap-svm.html[Additional administration for an AFX storage system SVM] for more information.

// table end
|===

== REST API

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| Balanced placement enhancements for Kubernetes storage orchestration
a| ONTAP 9.19.1 adds parameters currently available in the `/storage/volumes` REST API endpoint to the `/applications/containers` endpoint. This enhancement enables customers using NetApp Trident for Kubernetes storage orchestration to create volumes with https://docs.netapp.com/us-en/ontap/flexgroup/provision-automatically-task.html[ONTAP's native placement capability^].

// table end
|===

.Related information

* https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP 9 release highlights^]