---
sidebar: sidebar
permalink: release-notes/whats-new-9181.html
keywords: afx, release notes, what's new, 9.18.1
summary: "Learn about the new capabilities included with ONTAP 9.18.1 that are available with your AFX storage system."
---
= What's new in ONTAP 9.17.1 for AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the new capabilities included with ONTAP 9.18.1 that are available with your AFX storage system.

== Platforms

[cols="2,4" options="header"]
|===
// header row
| Update
| Description

| Enhanced volume placement
a| NetApp AFX automatically balances the placement of volumes across all the nodes in a cluster. With previous ONTAP releases, the placement algorithm was based on the number of volumes in the cluster. Every node is assigned the same number of volumes regardless of activity. Beginning with ONTAP 9.18.1, the algorithm has been enhanced to consider the performance of the nodes when placing or moving volumes. This results in improved performance balancing across the nodes in the AFX cluster and makes it much less likely that any single node becomes overloaded.

// table end
|===

.Related information

* https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP 9 release highlights^]
