---
sidebar: sidebar
permalink: release-notes/whats-new-9191.html
keywords: afx, release notes, what's new, 9.19.1
summary: "Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system."
---
= What's new in ONTAP 9.19.1 for AFX storage systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Learn about the new capabilities included with ONTAP 9.19.1 that are available with your AFX storage system.

[TIP]
Learn about the new and enhanced support for https://docs.netapp.com/us-en/ai-data-engine/release-notes/whats-new.html[AI Data Engine^].

== Performance and scale

[cols="2,4" options="header"]
|===

| Update
| Description

| Expanded AFX cluster size
a| ONTAP 9.19.1 supports the expansion of an AFX cluster to a maximum of 32 nodes. This allows you to scale your AFX storage system to meet the growing demands of your workloads and applications.

| Dynamic Storage Efficiency
a| Dynamic Storage Efficiency intelligently optimizes storage efficiency operations (compression, deduplication, and compaction) for large workloads that require high performance and maximum throughput. It automatically detects high-volume write conditions and temporarily suspends inline storage efficiency processes to prevent performance degradation during peak loads. When throughput drops, the inline efficiency operations are resumed which ensures storage savings are recovered without manual intervention. The feature is available on AFX storage systems and enabled by default with no configuration required.

| Cross File Sequential Read (CFSR)
a| Cross File Sequential Read can significantly improve read performance for certain media and entertainment workloads. The feature intelligently prefetches sequential video frames to dramatically improve throughput and reduce latency for video editing applications. Review link:../administer/additional-ontap-svm.html[Additional administration for an AFX storage system SVM] for more information.

| Global deduplication
a| Global deduplication extends ONTAP deduplication space savings to the entire Storage Availability Zone (SAZ). By eliminating duplicate data blocks across all the volumes in the SAZ, it can significantly improve storage efficiency and reduce total cost of ownership. The feature is enabled by default on AFX systems and operates transparently without the need for administrative configuration. Refer to link:../administer/additional-ontap-svm.html[Additional administration for an AFX storage system SVM] for more information.

|===

== REST API

[cols="2,4" options="header"]
|===

| Update
| Description

| Balanced placement enhancement for Kubernetes storage orchestration
a| ONTAP 9.19.1 adds six parameters currently available in the `/storage/volumes` REST API endpoint to the `/applications/containers` endpoint. This enhancement enables customers using NetApp Trident for Kubernetes storage orchestration to create volumes with ONTAP's native balanced placement capability.

| Counter Manager Cached Metrics
a| This is a monitoring feature that exports performance statistics from large ONTAP clusters which can be retrieved using the REST API. The metrics data, which is collected and cached by ONTAP at regular intervals, is anchored by manifests specifying the CM objects and counters. By decoupling collection from retrieval, the data can be shared among different clients which reduces system overhead. This design also scales well for large clusters as typically deployed with AFX storage systems.

|===
//https://docs.netapp.com/us-en/ontap/flexgroup/provision-automatically-task.html[ONTAP's placement capability^].

== Security

[cols="2,4" options="header"]
|===

| Update
| Description

| ARP/AI support for eligible SnapMirror primary volumes
a| ARP/AI supports eligible primary volumes in SnapMirror synchronous relationships with AFX systems. ARP/AI runs on the active read-write primary volume, creates primary-only ARP snapshots, and provides machine-learning-based ransomware detection.

| link:../administer/additional-ontap-cluster.html[Support for TLS hardware offload]
a| You can offload Transport Layer Security (TLS) encryption and decryption for your entire cluster to supported Ethernet cards.  This reduces CPU overhead and improves performance for systems using TLS.

|===

== Storage resource management

[cols="2,4" options="header"]
|===

| Update
| Description

| link:../administer/monitor-cluster-performance.html[System Manager support for storage availability zone capacity details.]
a| You can view your storage availability zone capacity details including space thresholds, space consumed by snapshots, and data reduction in System Manager. You can also set space usage thresholds to the percentage at which you want ONTAP to generate warning and critical alerts.

| link:../administer/additional-ontap-cluster.html[Support for modifying default settings that control automatic QoS throughput ceiling increases]
a| You can modify the default settings that control how QoS policy groups automatically increase the QoS throughput ceiling in response to short-term needs for higher performance. These settings cannot be modified in ONTAP 9.18.1 and earlier.
// table end
|===

== Upgrade

[cols="2,4" options="header"]
|===

| Update
| Description

| link:../administer/upgrade-ontap.html[Enhanced reporting for automated pre-upgrade checks]
a| When executing automated pre-upgrade checks, errors and warning are displayed separately to help you easily identify issues that must be resolved before you upgrade.


|===

.Related information

* https://docs.netapp.com/us-en/ontap/release-notes/index.html[ONTAP 9 release highlights^]

// 2026 May 07, ONTAPDOC-3603, ONTAPDOC-3501, ONTAPDOC-3614, ONTAPDOC-3680
